# Docker image. You can delete this line if not using Docker
image: python:3-stretch

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_ID/$CI_PROJECT_PATH
   
setup_dace:
  stage: build
  tags:
    - linux
  script:
    - echo "Reverting configuration to defaults"
    - rm -f ~/.dace.conf
    - echo "Clearing caches"
    - rm -rf .dacecache tests/.dacecache client_configs tests/client_configs
    - echo "Installing additional dependencies"
    - pip3 install --upgrade --user tensorflow-gpu==1.14.0
    - echo "Installing DaCe"
    - pip3 install --ignore-installed --upgrade --user .

test_diode_serialization:
  stage: test
  tags:
    - intel
    - linux
  script:
    - cd tests/diode/
    - ./serialize_test.sh

test_linux_cpu:
  stage: test
  tags: 
    - intel
    - linux
  script: 
    - export DACE_debugprint=1
    - tests/e2e_test.sh
    - tests/gemm_test.sh

test_linux_cuda:
  stage: test
  tags: 
    - cuda
    - linux
  script: 
    - export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
    - export PATH=/usr/local/cuda/bin:$PATH
    - export CUDA_ROOT=/usr/local/cuda
    - export DACE_debugprint=1
    - tests/cuda_test.sh
   
test_filter:
  stage: test
  tags: 
    - intel
    - linux
  script: 
    - cd tests/
    - ./diode_helper.sh 'python3 ../diode/diode_optscript_translator.py --file filter_test_opt.py -d2p "../diode/" | sh'
 
test_spmv:
  stage: test
  tags: 
    - intel
    - linux
  script: 
    - cd tests/
    - ./diode_helper.sh 'python3 ../diode/diode_optscript_translator.py --file spmv_test_opt.py -d2p "../diode/" | sh'

test_jacobi:
  stage: test
  tags: 
    - intel
    - linux
  script: 
    - cd tests/
    - ./diode_helper.sh 'python3 ../diode/diode_optscript_translator.py --file simple_stencil_test_opt.py -d2p "../diode/" | sh'

test_xilinx:
  stage: test
  tags:
    - xilinx
  script:
    - export PATH=/opt/Xilinx/SDx/2018.2/bin:$PATH
    - tests/xilinx_test.sh 0

test_polybench:
  stage: test
  tags:
    - intel
    - linux
  script:
    - NOSTATUSBAR=1 tests/polybench_test.sh

# Nightly tests

test_all:on-schedule:
  only:
    - schedules
  stage: test
  tags: 
    - intel
    - linux
  script:
    - export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
    - export PATH=/usr/local/cuda/bin:/opt/mpich3.2.11/bin:/opt/Xilinx/SDx/2018.2/bin:$PATH
    - export CUDA_ROOT=/usr/local/cuda
    - NOSTATUSBAR=1 xvfb-run ./test_all.sh

test_all_nostrict:on-schedule:
  only:
    - schedules
  stage: test
  tags: 
    - intel
    - linux
  script:
    - export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
    - export PATH=/usr/local/cuda/bin:/opt/mpich3.2.11/bin:/opt/Xilinx/SDx/2018.2/bin:$PATH
    - export CUDA_ROOT=/usr/local/cuda
    - export DACE_optimizer_automatic_strict_transformations=0
    - NOSTATUSBAR=1 xvfb-run ./test_all.sh
