dist: bionic
language: python
python:
  - "3.7"  

env:
  - DACE_optimizer_automatic_strict_transformations=1
  - DACE_optimizer_automatic_strict_transformations=0

# Dependencies
before_install:
  - sudo apt-get install libyaml-dev cmake
  # Instrumentation dependencies
  - sudo apt-get install libpapi-dev papi-tools

install:
  - pip install ".[testing]" .
  - pip install coverage codecov
  - if [ $DACE_optimizer_automatic_strict_transformations -eq 1 ]; then pip install tensorflow==1.15.0; fi

before_script:
  - papi_avail

script:
  - export NOSTATUSBAR=1
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - export COVERAGE_RCFILE=`pwd`/.coveragerc
  - export PYTHON_BINARY="coverage run --source=`pwd`/dace --parallel-mode"
  - export DACE_optimizer_interface=" "
  - ./test_all.sh
  - cd tests; coverage combine . */; coverage report; coverage xml

after_success:
  - codecov
