dist: xenial
language: python
python:
  - "3.7"  

env:
  - DACE_optimizer_automatic_strict_transformations=1
  - DACE_optimizer_automatic_strict_transformations=0

# Dependencies
before_install:
  - sudo apt-get install libyaml-dev cmake

install:
  - pip install ".[test]" .

script:
  - export NOSTATUSBAR=1
  - export PYTHONPATH=`pwd`:$PYTHONPATH
  - export PYTHON_BINARY="coverage run --source=`pwd`/dace --parallel-mode"
  - ./test_all.sh
  - cd tests; coverage combine; coverage report
