name: Heterogeneous Tests

on:
  push:
    branches: [ master, ci-fix ]
  pull_request:
    branches: [ master, ci-fix ]

jobs:
  test-heterogeneous:
    runs-on: [self-hosted, linux]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install dependencies
      run: |
        rm -f ~/.dace.conf
        rm -rf .dacecache tests/.dacecache
        . /opt/setupenv
        python -m pip install --upgrade pip
        pip install flake8 pytest-xdist coverage codecov
        pip install mpi4py pytest-mpi
        pip uninstall -y dace
        pip install -e ".[testing]"

    - name: Test dependencies
      run: |
        papi_avail

    - name: Run parallel pytest 
      run: |
        export DACE_cache=unique
        export DACE_optimizer_interface=" "
        . /opt/setupenv
        pytest -n auto --cov-report=xml --cov=dace --tb=short -m "verilator or mkl or papi"
        codecov

    - name: Run MPI tests
      run: |
        export NOSTATUSBAR=1
        export DACE_cache=single
        export COVERAGE_RCFILE=`pwd`/.coveragerc
        export PYTHON_BINARY="coverage run --source=dace --parallel-mode"
        . /opt/setupenv
        ./tests/mpi_test.sh

        
    - name: Test MPI with pytest
      run: |
        export NOSTATUSBAR=1
        export DACE_testing_serialization=1
        export DACE_testing_deserialize_exception=1
        export DACE_cache=unique
        export DACE_optimizer_interface=" "
        mpirun -n 2 coverage run --source=dace --parallel-mode -m pytest -x --with-mpi --tb=short -m "mpi"
    
    - name: Test ScaLAPACK PBLAS with pytest
      run: |
        export NOSTATUSBAR=1
        export DACE_testing_serialization=1
        export DACE_testing_deserialize_exception=1
        export DACE_cache=unique
        export DACE_optimizer_interface=" "
        for i in {1..8}
        do
          mpirun -n $i coverage run --source=dace -m pytest -x --with-mpi --tb=short -m "scalapack"
        done

    - name: Report overall coverage
      run: |
        export COVERAGE_RCFILE=`pwd`/.coveragerc
        . /opt/setupenv
        coverage combine . */; coverage report; coverage xml
        codecov
